version: '2'

networks:
  mynet1:
    ipam:
      config:
        - subnet: 172.30.0.0/16
services:
  web:
    build: .
    ports:
      - "3100:3100"
    depends_on:
      db:
        condition: service_healthy
    networks:
      mynet1:
        ipv4_address: 172.30.0.2
  db:
    container_name: mysql
    image: mysql:5.7
    # cpus: "2"
    # mem_limit: "2G"
    restart: "always"
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_USER: "admin"
      MYSQL_PASS: "123456"
      MYSQL_DATABASE: "yuecaidb"
    # ports:
    #   - "3306:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=123456 --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5
    networks:
      mynet1:
        ipv4_address: 172.30.0.3


